name: CI build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - run: npm ci
      - name: Debug wollok-web-tools files
        run: |
          npm ls wollok-web-tools
          ls -R node_modules/wollok-web-tools/dist || true
      - name: Unit Tests
        run: npm run test-with-coverage
      - name: Update coverage badge
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage/coverage-final.json
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
